### ISSUE TITLE
Error while building

### ISSUE THREAD

**Issue by utkarsh2102** [fog/fog-rackspace#31]
Hi,

There seems to be one of the error while building the package. Here is what it says:

```
  Fog::Rackspace::LoadBalancers | load_balancer_get_stats (rackspace)
    Initialization parameters must be an attributes hash, got Fog::Rackspace::LoadBalancers::VirtualIp     <Fog::Rackspace::LoadBalancers::VirtualIp
      id="3817",
      address="732.903.662.424",
      type="PUBLIC",
      ip_version="IPV4"
    > (ArgumentError)
      /usr/lib/ruby/vendor_ruby/fog/core/collection.rb:86:in `new'
      /usr/lib/ruby/vendor_ruby/fog/core/collection.rb:76:in `block in load'
      /usr/lib/ruby/vendor_ruby/fog/core/collection.rb:18:in `each'
      /usr/lib/ruby/vendor_ruby/fog/core/collection.rb:18:in `each'
      /usr/lib/ruby/vendor_ruby/fog/core/collection.rb:76:in `load'
      /home/utkarsh2102/utkarsh/rackspace/ruby-fog-rackspace/lib/fog/rackspace/models/load_balancers/load_balancer.rb:111:in `virtual_ips='
      /usr/lib/ruby/vendor_ruby/fog/core/attributes.rb:134:in `block in merge_attributes'
      /usr/lib/ruby/vendor_ruby/fog/core/attributes.rb:129:in `each_pair'
      /usr/lib/ruby/vendor_ruby/fog/core/attributes.rb:129:in `merge_attributes'
      /usr/lib/ruby/vendor_ruby/fog/core/model.rb:51:in `reload'
      /usr/lib/ruby/vendor_ruby/fog/core/model.rb:73:in `block in wait_for'
      /usr/lib/ruby/vendor_ruby/fog/core/wait_for.rb:7:in `block in wait_for'
      /usr/lib/ruby/vendor_ruby/fog/core/wait_for.rb:6:in `loop'
      /usr/lib/ruby/vendor_ruby/fog/core/wait_for.rb:6:in `wait_for'
      /usr/lib/ruby/vendor_ruby/fog/core/model.rb:72:in `wait_for'
      /home/utkarsh2102/utkarsh/rackspace/ruby-fog-rackspace/tests/rackspace/helper.rb:21:in `given_a_load_balancer'
      /home/utkarsh2102/utkarsh/rackspace/ruby-fog-rackspace/tests/rackspace/requests/load_balancers/get_stats_tests.rb:4:in `block (2 levels) in <top (required)>'
      /home/utkarsh2102/utkarsh/rackspace/ruby-fog-rackspace/tests/rackspace/helper.rb:10:in `instance_eval'
      /home/utkarsh2102/utkarsh/rackspace/ruby-fog-rackspace/tests/rackspace/helper.rb:10:in `given_a_load_balancer_service'
      /home/utkarsh2102/utkarsh/rackspace/ruby-fog-rackspace/tests/rackspace/requests/load_balancers/get_stats_tests.rb:3:in `block in <top (required)>'
      /usr/lib/ruby/vendor_ruby/shindo.rb:79:in `instance_eval'
      /usr/lib/ruby/vendor_ruby/shindo.rb:79:in `tests'
      /usr/lib/ruby/vendor_ruby/shindo.rb:38:in `initialize'
      /usr/lib/ruby/vendor_ruby/shindo.rb:13:in `new'
      /usr/lib/ruby/vendor_ruby/shindo.rb:13:in `tests'
      /home/utkarsh2102/utkarsh/rackspace/ruby-fog-rackspace/tests/rackspace/requests/load_balancers/get_stats_tests.rb:1:in `<top (required)>'
      /usr/lib/ruby/vendor_ruby/shindo/bin.rb:61:in `load'
      /usr/lib/ruby/vendor_ruby/shindo/bin.rb:61:in `block (2 levels) in run_in_thread'
      /usr/lib/ruby/vendor_ruby/shindo/bin.rb:58:in `each'
      /usr/lib/ruby/vendor_ruby/shindo/bin.rb:58:in `block in run_in_thread'
```

**Comment by utkarsh2102** [comment]
Hey,
Any idea how to patch that up?
